# Generated by Django 2.2.7 on 2019-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='fb_app_id',
            field=models.CharField(default='test_id', max_length=255),
            preserve_default=False,
        ),
    ]
