# Generated by Django 2.2.7 on 2019-11-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_to_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
