# Generated by Django 2.2.7 on 2019-11-18 22:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=256)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], max_length=2)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('featured_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
