# Generated by Django 2.2.13 on 2021-02-05 12:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], max_length=2)),
                ('location', models.CharField(choices=[('BOH', 'After <head>'), ('EOH', 'Before </head>'), ('BOB', 'After <body>'), ('EOB', 'Before </body>')], max_length=3)),
                ('snippet', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
