# Generated by Django 2.2.13 on 2021-02-07 23:07

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmation_number',
            field=models.CharField(default=accounts.helpers.generate_confirmation_number, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
